name: secure_report
description: SecureReport mobile application
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: any
  cloud_functions: any
  firebase_auth: any
  firebase_core: any
  firebase_messaging: any
  firebase_storage: any
  geolocator: any
  google_sign_in: any
  http: any
  image_picker: any
  intl: any
  mobile_scanner: any
  shared_preferences: any
  uuid: any
  flutter_riverpod: any

flutter:
  uses-material-design: true
